name: PHPStan

on:
  push:
  pull_request:

permissions: read-all

jobs:
  build:
    uses: The-FireHub-Project/.github/.github/workflows/RunCommandOnMatrix.yml@master
    with:
      title: "Run PHPStan"
      phpVersions: '["8.5"]'
      phpExtensions: "zip, curl, openssl, mbstring"
      tools: "phpstan:2.x"
      command: "phpstan analyse"
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}